export const RECEIVE_ALL_EVENTS = "EVENTS:RECEIVE_ALL_EVENTS";
export const RECEIVE_EVENT = "EVENTS:RECEIVE_EVENT";
export const SET_EVENTS_LOADING = "EVENTS:SET_EVENTS_LOADING";
export const UPDATE_EVENT = "EVENTS:UPDATE_EVENT";
export const DELETE_EVENT = "EVENTS:DELETE_EVENT";
export const EVENT_IS_LOADING = "EVENTS:EVENT_IS_LOADING";
