export const RECEIVE_USER_DATA = "AUTHENTICATION:RECEIVE_USER_LOGIN";
export const REMOVE_USER_DATA = "AUTHENTICATION:REMOVE_USER_DATA";
export const SET_IS_LOADING = "AUTHENTICATION:SET_IS_LOADING";
export const RECEIVE_REQUEST_ERROR = "AUTHENTICATION:RECEIVE_REQUEST_ERROR";
